#ifndef HMIEvents_H
#define HMIEvents_H
#include <QObject>


class HMIEvents: public QObject
{
    Q_OBJECT
    Q_ENUMS( EVT_SCREEN_OPERATION )
    Q_ENUMS( EVT_SCREEN_TRANSITION )
    Q_ENUMS( KEY_STATE )
public:
    enum EVT_SCREEN_OPERATION
    {
        // MAIN HOME SCREEN
        //00-04
        EVT_GOTO_ALL_SCREEN_ITEMS,
        EVT_MAIN_LIST_ITEMCLICKED,
        EVT_SUBMENU_BLUELINK_ITEMCLICKED,
        EVT_SUBMENU_MEDIA_ITEMCLICKED,
        EVT_SUBMENU_SETUP_ITEMCLICKED,
        //05-09
        EVT_SUBMENU_DATASERVICE_ITEMCLICKED,
        EVT_SUBMENU_INFORMATION_ITEMCLICKED,

        EVT_MYMENU_ITEMCLICKED,
        EVT_HOME_LIST_PAGE0_MOVING,
        EVT_HOME_LIST_PAGE1_MOVING,
        //10-14
        EVT_HOME_LIST_PAGE2_MOVING,
        EVT_HOME_LIST_PAGE3_MOVING,
        EVT_HOME_LIST_PAGE4_MOVING,
        EVT_HOME_NOTIFY_SHOW_WIDGET_PAGE,
        EVT_MOVE_MY_MENU,
        //15-18
        EVT_ADD_DEL_MY_MENU,
        EVT_SHOW_POPUP_AD_NOTIFY,
        EVT_MOVE_FOCUS_STATE_TO_AW,
        EVT_MOVE_FOCUS_STATE_TO_THIS_APP,
        //19-23
        EVT_OPEN_AW_OPION_MENU,
        EVT_OPEN_OPION_MENU,
        EVT_SET_AW_WIDGET,
        EVT_CLICK_DISP_OFF,
        EVT_HOME_ICON_STATE,
        //24-25
        EVT_HOME_SOUND_BEEP_PLAY,
        EVT_OPEN_SXM_SUBCRIPTION,
        //26 - 27
        EVT_REQUEST_SHOW_POPUP,
        EVT_REQUEST_HIDE_POPUP,
        //28
        EVT_GOTO_HOME_CUSTOMIZE,
        //29
        EVT_CLOSE_SETTING_WIDGET,
        //30
        EVT_POPUP_YES_BUTTON_CLICK,
        EVT_POPUP_NO_BUTTON_CLICK,
        EVT_REQUEST_CALL_SXM,

        // 41
        EVT_CUSTOMIZE_BACK_TO_SETUP,
        // 42
        EVT_BACK_TO_MAIN_LIST = 40,

        KEY_EVT_MAX,
    };

    enum EVT_SCREEN_TRANSITION
    {
        EVT_GOTO_SCREEN_WIDE_ALL_ITEMS = KEY_EVT_MAX + 10,
        EVT_GOTO_SCREEN_NORM_ALL_ITEMS,
        EVT_GOTO_SCREEN_SUBMENU_SETUP,
        EVT_GOTO_SCREEN_SUBMENU_MEDIA,
        EVT_GOTO_SCREEN_DATA_SERVICE,
        EVT_GOTO_SCREEN_SUBMENU_INFOMATION,
        EVT_GOTO_SCREEN_SUBMENU_EDIT_WIDGETS,
        EVT_GOTO_SCREEN_SUBMENU_EDIT_MENUS,

        EVT_GOTO_MENU_MYMENU,
        EVT_GOTO_MENU_MYMENU_SHORTCUTS_1ST,
        EVT_GOTO_MENU_MYMENU_SHORTCUTS_2ND,
        EVT_GOTO_MENU_MYMENU_SHORTCUTS_3RD,
        EVT_GOTO_MENU_MYMENU_DELETE,
        EVT_GOTO_MENU_MYMENU_MOVE,
        EVT_GOTO_HOME_CUSTOMIZE_NORM,
        EVT_GOTO_HOME_CUSTOMIZE_WIDE,
        EVT_GOTO_HOME_SETTING_WIDGET,
        EVT_GOTO_SCREEN_ALL_MENUS,

        EVT_GOTO_QUICK_GUIDE_BASICLAYOUT,
        EVT_GOTO_SCREEN_HOMESCREEN_QUICK_GUIDE,
        //20170623002_add+s
        EVT_GOTO_SCREEN_SUBMENU_SETTING_HOMESCREEN,
        //20170623002_add+e
        // Event Back
        EVT_BACK_TO_PREV_SCREEN = 65535,
        EVT_TRANSITON_MAX,
    };
};

#endif // HMIEvents_H
